Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [13]:
import numpy as np

vector = np.arange(1, 11)
vector


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [14]:
matrix = np.zeros((3, 3))
matrix


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [15]:
random_matrix_5x5 = np.random.randint(1, 11, size=(5, 5))
print("\nМасив 5x5, заповнений випадковими цілими числами від 1 до 10:")
print(random_matrix_5x5)


Масив 5x5, заповнений випадковими цілими числами від 1 до 10:
[[ 8 10 10  5  2]
 [ 2  8  9  9  7]
 [ 6  1  7  7  1]
 [ 8  9  5  1  3]
 [10  1  5  8  6]]


Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [16]:
random_matrix_4x4 = np.random.rand(4, 4)
print("Масив 4x4, заповнений випадковими дійсними числами від 0 до 1:")
print(random_matrix_4x4)

Масив 4x4, заповнений випадковими дійсними числами від 0 до 1:
[[0.2517947  0.40434262 0.90895322 0.0279615 ]
 [0.13448174 0.76503428 0.08473805 0.15825891]
 [0.77782173 0.57054188 0.68544588 0.92107992]
 [0.19618683 0.88415311 0.12011833 0.63919404]]


Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [17]:
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)

print("Перший масив:")
print(array1)

print("Другий масив:")
print(array2)

addition = np.add(array1, array2)
print("\nПоелементне додавання:")
print(addition)

subtraction = np.subtract(array1, array2)
print("\nПоелементне віднімання:")
print(subtraction)

multiplication = np.multiply(array1, array2)
print("\nПоелементне множення:")
print(multiplication)


Перший масив:
[6 8 8 1 2]
Другий масив:
[ 4 10  3  5  9]

Поелементне додавання:
[10 18 11  6 11]

Поелементне віднімання:
[ 2 -2  5 -4 -7]

Поелементне множення:
[24 80 24  5 18]


Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [18]:
vector1 = np.random.random(7)
vector2 = np.random.random(7)

print("Перший вектор:")
print(vector1)

print("Другий вектор:")
print(vector2)

dot_product = np.dot(vector1, vector2)
print("\nСкалярний добуток:")
print(dot_product)


Перший вектор:
[0.22866596 0.54229262 0.71644086 0.39574264 0.81549224 0.62032493
 0.24745693]
Другий вектор:
[0.09757913 0.8643388  0.7511896  0.78612818 0.38218785 0.83436301
 0.32264727]

Скалярний добуток:
2.2494136459264773


Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [19]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))

print("Перша матриця (2x2):")
print(matrix1)

print("Друга матриця (2x3):")
print(matrix2)

product = np.dot(matrix1, matrix2)
print("\nДобуток матриць (2x2 і 2x3):")
print(product)


Перша матриця (2x2):
[[7 6]
 [7 5]]
Друга матриця (2x3):
[[ 9  9  6]
 [10  5  2]]

Добуток матриць (2x2 і 2x3):
[[123  93  54]
 [113  88  52]]


Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [20]:
matrix = np.random.randint(1, 11, size=(3, 3))

print("Матриця 3x3:")
print(matrix)

try:
    inverse_matrix = np.linalg.inv(matrix)
    print("\nОбернена матриця:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("\nМатриця є виродженою і не має оберненої матриці.")

Матриця 3x3:
[[ 3  5  8]
 [ 3  5  5]
 [ 9  5 10]]

Обернена матриця:
[[-0.27777778  0.11111111  0.16666667]
 [-0.16666667  0.46666667 -0.1       ]
 [ 0.33333333 -0.33333333  0.        ]]


Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [21]:
matrix = np.random.rand(4, 4)

print("Матриця 4x4:")
print(matrix)

transposed_matrix = np.transpose(matrix)
print("\nТранспонована матриця:")
print(transposed_matrix)

Матриця 4x4:
[[0.33554182 0.09012247 0.24846489 0.26680126]
 [0.3406758  0.67114937 0.57801958 0.54619678]
 [0.09248789 0.49597404 0.08474617 0.20658636]
 [0.47026882 0.73585214 0.94828549 0.84326597]]

Транспонована матриця:
[[0.33554182 0.3406758  0.09248789 0.47026882]
 [0.09012247 0.67114937 0.49597404 0.73585214]
 [0.24846489 0.57801958 0.08474617 0.94828549]
 [0.26680126 0.54619678 0.20658636 0.84326597]]


Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [22]:
matrix = np.random.randint(1, 11, size=(3, 4))

vector = np.random.randint(1, 11, size=4)

print("Матриця 3x4:")
print(matrix)

print("\nВектор розміром 4:")
print(vector)

result = np.dot(matrix, vector)
print("\nРезультат множення матриці на вектор:")
print(result)

Матриця 3x4:
[[ 7  7 10  9]
 [ 2  9  8  7]
 [ 4  1  7  7]]

Вектор розміром 4:
[ 1  5 10  9]

Результат множення матриці на вектор:
[223 190 142]


Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [23]:
matrix = np.random.rand(2, 3)

vector = np.random.rand(3)

print("Матриця 2x3:")
print(matrix)

print("\nВектор розміром 3:")
print(vector)

result = np.dot(matrix, vector)
print("\nРезультат множення матриці на вектор:")
print(result)

Матриця 2x3:
[[0.94089347 0.38894681 0.79346724]
 [0.64179604 0.44250825 0.52288537]]

Вектор розміром 3:
[0.80197455 0.33801339 0.96822604]

Результат множення матриці на вектор:
[1.65429749 1.17054904]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [24]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

print("Перша матриця (2x2):")
print(matrix1)

print("Друга матриця (2x2):")
print(matrix2)

elementwise_multiplication = np.multiply(matrix1, matrix2)
print("\nПоелементне множення матриць:")
print(elementwise_multiplication)

Перша матриця (2x2):
[[1 1]
 [3 6]]
Друга матриця (2x2):
[[3 2]
 [5 5]]

Поелементне множення матриць:
[[ 3  2]
 [15 30]]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [25]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

print("Перша матриця (2x2):")
print(matrix1)

print("Друга матриця (2x2):")
print(matrix2)

product = np.dot(matrix1, matrix2)
print("\nДобуток матриць:")
print(product)

Перша матриця (2x2):
[[ 3  6]
 [ 2 10]]
Друга матриця (2x2):
[[3 8]
 [2 2]]

Добуток матриць:
[[21 36]
 [26 36]]


Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [26]:
matrix = np.random.randint(1, 101, size=(5, 5))

sum_of_elements = np.sum(matrix)

print("Матриця:")
print(matrix)
print("Сума елементів матриці:", sum_of_elements)

Матриця:
[[35 93 94 29 52]
 [81  5 39 54 31]
 [57 14 70 46 85]
 [57 41 50 35 37]
 [52 36 90 98 60]]
Сума елементів матриці: 1341


Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [28]:
matrix1 = np.random.randint(1, 11, size=(4, 4))

matrix2 = np.random.randint(1, 11, size=(4, 4))

difference_matrix = matrix1 - matrix2

print("Перша матриця:")
print(matrix1)
print("\nДруга матриця:")
print(matrix2)
print("\nРізниця між матрицями:")
print(difference_matrix)

Перша матриця:
[[ 2  3  8  9]
 [ 8  5  3 10]
 [ 7  4  7  5]
 [ 1  9  8  5]]

Друга матриця:
[[7 2 2 4]
 [3 3 5 8]
 [9 5 7 5]
 [7 1 1 6]]

Різниця між матрицями:
[[-5  1  6  5]
 [ 5  2 -2  2]
 [-2 -1  0  0]
 [-6  8  7 -1]]


Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [29]:
matrix = np.random.rand(3, 3)

row_sums = np.sum(matrix, axis=1, keepdims=True)

print("Матриця:")
print(matrix)
print("\nСуми елементів кожного рядка матриці (вектор-стовпчик):")
print(row_sums)

Матриця:
[[0.6511922  0.86934431 0.30015977]
 [0.29807858 0.97157112 0.13135169]
 [0.87490312 0.76697298 0.2547874 ]]

Суми елементів кожного рядка матриці (вектор-стовпчик):
[[1.82069628]
 [1.40100139]
 [1.89666349]]


Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [30]:
matrix = np.random.randint(1, 11, size=(3, 4))

squared_matrix = np.square(matrix)

print("Початкова матриця:")
print(matrix)
print("\nМатриця з квадратами чисел:")
print(squared_matrix)

Початкова матриця:
[[9 3 4 7]
 [2 5 8 2]
 [2 1 8 6]]

Матриця з квадратами чисел:
[[81  9 16 49]
 [ 4 25 64  4]
 [ 4  1 64 36]]


Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [31]:
vector = np.random.randint(1, 51, size=4)

sqrt_vector = np.sqrt(vector)

print("Початковий вектор:")
print(vector)
print("\nВектор з квадратними коренями:")
print(sqrt_vector)

Початковий вектор:
[15 25 39 31]

Вектор з квадратними коренями:
[3.87298335 5.         6.244998   5.56776436]
